# .github/workflows/release-and-deploy.yml
name: Release and Deploy Payment Tracker

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  FUNCTION_NAME: payment-extractor

jobs:
  # Step 1: Create release with versioning and changelog
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Create Release
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: python
          package-name: payment-tracker

  # Step 2: Deploy only when a release is created
  deploy:
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy $FUNCTION_NAME \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --region $GCP_REGION \
          --source . \
          --entry-point payment_extractor \
          --memory 512MB \
          --timeout 540s \
          --set-env-vars GCP_PROJECT_ID=$GCP_PROJECT_ID,VERSION=${{ needs.release.outputs.version }} \
          --set-secrets "GMAIL_APP_PASSWORD=gmail-app-password:latest,NOTION_TOKEN=notion-api-token:latest,NOTION_DATABASE_ID=notion-database-id:latest"

    - name: Update Cloud Scheduler
      run: |
        gcloud scheduler jobs delete payment-tracker-monthly \
          --location=$GCP_REGION \
          --quiet || true
        
        gcloud scheduler jobs create http payment-tracker-monthly \
          --location $GCP_REGION \
          --schedule "0 9 1,15 * *" \
          --uri "https://$GCP_REGION-$GCP_PROJECT_ID.cloudfunctions.net/$FUNCTION_NAME" \
          --http-method POST \
          --headers "Content-Type=application/json" \
          --message-body '{"source": "scheduler"}' \
          --description "Payment tracker - twice monthly (v${{ needs.release.outputs.version }})" \
          --time-zone "America/New_York"

    - name: Test deployment
      run: |
        FUNCTION_URL="https://$GCP_REGION-$GCP_PROJECT_ID.cloudfunctions.net/$FUNCTION_NAME"
        echo "Testing deployment for version ${{ needs.release.outputs.version }}"
        
        RESPONSE=$(curl -s -X POST "$FUNCTION_URL" \
          -H "Content-Type: application/json" \
          -d '{"test": true}' || echo "Connection failed")
        
        echo "Response: $RESPONSE"

    - name: Deployment Summary
      run: |
        echo "🚀 Deployment completed for version ${{ needs.release.outputs.version }}"
        echo "📦 Function: https://$GCP_REGION-$GCP_PROJECT_ID.cloudfunctions.net/$FUNCTION_NAME"
        echo "⏰ Schedule: 1st and 15th at 9 AM EST"
        echo "🏷️ Release: https://github.com/${{ github.repository }}/releases/tag/${{ needs.release.outputs.tag_name }}"